### PR TITLE
Repository setup

### PR DESCRIPTION
**Pull request by MaSpeng**

### CODE REVIEW

**Comment by MaSpeng** [comment]
@FrankGiesecke, @schroedan, could you please provide me an advise about the chosen LICENSE `MIT` if this is ok for our use case or do we need another one?

**Comment by FrankGiesecke** [comment]
Please add a validation for the Dockerfile (e.g. using Codacy)

**Comment by FrankGiesecke** [comment]
IMHO: As the original PHP image is under `MIT`, we should keep this license model for our image.

**Comment by schroedan** [comment]
1. MIT is okay as @FrankGiesecke mentioned before
2. you may use https://github.com/hadolint/hadolint to lint `Dockerfile`s at Travis but you don't need to validate them - when they are invalid they won't build at Travis

**Comment by FrankGiesecke** [comment]
Validating the `Dockerfile` using a tool like hadolint will help us to keep the file content clean.

**Comment by MaSpeng** [comment]
@FrankGiesecke @schroedan Thanks for your advice. So I leave the license MIT. For quality testing I have added `codacy` because it uses `hadolint` for its testing.

**Pull request merged**
